### ISSUE TITLE
[BUG] can not work normally

### ISSUE THREAD

**Issue by DyroS3** [baguscodestudio/bcs_identity#2]
### **1. My cfg**
```cfg
## ESX Legacy 1.9.4 Core
ensure es_extended # ESX 核心 勿动!!!
ensure [Core] # ESX 其他核心资源

## ESX Addons
stop basic-gamemode 
ensure bcs_identity
ensure esx_society # 请勿更改society的启动顺序
ensure [Esx_Addons] # ESX Addons 资源
```
### **3. I don't see any bugs in the console or otherwise**

[ **New player enters server video**](https://streamable.com/8vx4zg)

**Comment by baguscodestudio** [comment]
You can try redownloading the v1.1 see if it fixes it

**Comment by DyroS3** [comment]
> You can try redownloading the v1.1 see if it fixes it

Not work when I use v1.1, by the way I use `[illenium-appearance]`, I didn't see any errors

**Comment by baguscodestudio** [comment]
It should be the same with illenium-appearance, did you remove esx_identity? Like in the [core] folder? are you using multichar? did you enable it in the config of es_extended?

**Comment by DyroS3** [comment]
1. already remove esx_identity
![image](https://github.com/baguscodestudio/bcs_identity/assets/64310374/5baecdaa-1531-4c2f-b8ca-31199d865825)


2. I am using multichar
```lua
Config.Multichar                = GetResourceState("esx_multicharacter") ~= "missing"
Config.Identity                 = true -- Select a characters identity data before they have loaded in (this happens by default with multichar)
```

**Comment by baguscodestudio** [comment]
Hopefully it hasn't been that long. I just found out that I modified the esx_multicharacter. Go to your client/main.lua of multicharacter then replace this `'esx_identity:showRegisterIdentity'` with `'bcs_identity:startRegister'`

**Comment by DyroS3** [comment]
> Hopefully it hasn't been that long. I just found out that I modified the esx_multicharacter. Go to your client/main.lua of multicharacter then replace this `'esx_identity:showRegisterIdentity'` with `'bcs_identity:startRegister'`


Never mind about that, now it's working. Thanks for your reply and your open source project

**Comment by DyroS3** [comment]
![image](https://github.com/baguscodestudio/bcs_identity/assets/64310374/060ea5e3-82dd-414a-a910-6c9a395ba762)
I want to know why firstname is not compatible with Chinese or other languages, but lastname is supported.
Check out this question if you can, I think it's important

**Comment by baguscodestudio** [comment]
Should be fixed https://github.com/baguscodestudio/bcs_identity/commit/856fc8eb2ed0c37717d6f34373154ec10bd6e61f
